'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSParametrosCOM_CERT
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ParametroInterfazKeySoapBinding", [Namespace]:="http://service.ws.comp.bn.com.pe")>  _
    Partial Public Class ParametroInterfazKeyService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private datoParametroServiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.7.106.36:9080/WSParamService/services/ParametroInterfazKey"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event datoParametroServiceCompleted As datoParametroServiceCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service.ws.comp.bn.com.pe", ResponseNamespace:="http://service.ws.comp.bn.com.pe", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function datoParametroService(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)> ByVal sistema As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)> ByVal cuenta As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)> ByVal semilla As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")> ByVal llave() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)> ByVal idUsuario As String) As <System.Xml.Serialization.XmlElementAttribute("datoParametroServiceReturn", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)> SistemaParametro
            Dim results() As Object = Me.Invoke("datoParametroService", New Object() {sistema, cuenta, semilla, llave, idUsuario})
            Return CType(results(0),SistemaParametro)
        End Function
        
        '''<remarks/>
        Public Function BegindatoParametroService(ByVal sistema As String, ByVal cuenta As String, ByVal semilla As String, ByVal llave() As Byte, ByVal idUsuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("datoParametroService", New Object() {sistema, cuenta, semilla, llave, idUsuario}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EnddatoParametroService(ByVal asyncResult As System.IAsyncResult) As SistemaParametro
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SistemaParametro)
        End Function
        
        '''<remarks/>
        Public Overloads Sub datoParametroServiceAsync(ByVal sistema As String, ByVal cuenta As String, ByVal semilla As String, ByVal llave() As Byte, ByVal idUsuario As String)
            Me.datoParametroServiceAsync(sistema, cuenta, semilla, llave, idUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub datoParametroServiceAsync(ByVal sistema As String, ByVal cuenta As String, ByVal semilla As String, ByVal llave() As Byte, ByVal idUsuario As String, ByVal userState As Object)
            If (Me.datoParametroServiceOperationCompleted Is Nothing) Then
                Me.datoParametroServiceOperationCompleted = AddressOf Me.OndatoParametroServiceOperationCompleted
            End If
            Me.InvokeAsync("datoParametroService", New Object() {sistema, cuenta, semilla, llave, idUsuario}, Me.datoParametroServiceOperationCompleted, userState)
        End Sub
        
        Private Sub OndatoParametroServiceOperationCompleted(ByVal arg As Object)
            If (Not (Me.datoParametroServiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent datoParametroServiceCompleted(Me, New datoParametroServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://bean.ws.comp.bn.com.pe")>  _
    Partial Public Class SistemaParametro
        
        Private aliasSistemaField As String
        
        Private grupoParametroField() As GrupoParametro
        
        Private procesoField As ReturnProceso
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property aliasSistema() As String
            Get
                Return Me.aliasSistemaField
            End Get
            Set
                Me.aliasSistemaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property grupoParametro() As GrupoParametro()
            Get
                Return Me.grupoParametroField
            End Get
            Set
                Me.grupoParametroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property proceso() As ReturnProceso
            Get
                Return Me.procesoField
            End Get
            Set
                Me.procesoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://bean.ws.comp.bn.com.pe")>  _
    Partial Public Class GrupoParametro
        
        Private tipoGrupoField As String
        
        Private aliasDescripGrupoField As String
        
        Private aliasGrupoField As String
        
        Private parametroField() As Parametro
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property tipoGrupo() As String
            Get
                Return Me.tipoGrupoField
            End Get
            Set
                Me.tipoGrupoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property aliasDescripGrupo() As String
            Get
                Return Me.aliasDescripGrupoField
            End Get
            Set
                Me.aliasDescripGrupoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property aliasGrupo() As String
            Get
                Return Me.aliasGrupoField
            End Get
            Set
                Me.aliasGrupoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property parametro() As Parametro()
            Get
                Return Me.parametroField
            End Get
            Set
                Me.parametroField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://bean.ws.comp.bn.com.pe")>  _
    Partial Public Class Parametro
        
        Private aliasParamField As String
        
        Private campoParamField As String
        
        Private descripcionParamField As String
        
        Private tipoParamField As String
        
        Private valorParamField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property aliasParam() As String
            Get
                Return Me.aliasParamField
            End Get
            Set
                Me.aliasParamField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property campoParam() As String
            Get
                Return Me.campoParamField
            End Get
            Set
                Me.campoParamField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property descripcionParam() As String
            Get
                Return Me.descripcionParamField
            End Get
            Set
                Me.descripcionParamField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property tipoParam() As String
            Get
                Return Me.tipoParamField
            End Get
            Set
                Me.tipoParamField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property valorParam() As String
            Get
                Return Me.valorParamField
            End Get
            Set
                Me.valorParamField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://bean.ws.comp.bn.com.pe")>  _
    Partial Public Class ReturnProceso
        
        Private codigoField As String
        
        Private descripcionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub datoParametroServiceCompletedEventHandler(ByVal sender As Object, ByVal e As datoParametroServiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class datoParametroServiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SistemaParametro
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SistemaParametro)
            End Get
        End Property
    End Class
End Namespace
